execution_env=local
#execution_env=remote


appURL=http://localhost/opencart/upload/
#appURL=https://tutorialsninja.com/demo/


email=chaudhuri28soumya@gmail.com
password=TestAutomationArchitect@99

searchProductName=iPhone