execution_env=local
#execution_env=remote


appURL=http://localhost/opencart/upload/
#appURL=https://tutorialsninja.com/demo/


email=chaudhuri28soumya@gmail.com
password=TestAutomationArchitect@99


searchProductName=iPhone

#Spark-Reporter Configuration
document_title=Opencart Automation Report
report_name=Opencart Functional Testing

#Extent_Report Configuration
application_name=Opencart
module_name=Admin
sub_module_name=Customers
environment_name=QA

